AGENT_LOG_FILE: logs/agent.log
API_KEY: <enter API Key>
LOG_FILE_UE1: logs/UE1_iperfc.log
LOG_FILE_UE2: logs/UE2_iperfc.log
gnb_logs: logs/gNodeB_docker.log
interrupt_after: 30
model_name: nvidia/llama-3.1-nemotron-safety-guard-8b-v3
reconfig_script_path: ../llm-slicing-5g-lab/change_rc_slice.sh
GRAPHANA_DASHBOARD: <enter Graphana dashboard id>
