AGENT_LOG_FILE: logs/agent.log
LOG_FILE_UE1: ../llm-slicing-5g-lab/logs/UE1_iperfc.log
LOG_FILE_UE2: ../llm-slicing-5g-lab/logs/UE2_iperfc.log
gnb_logs: ../llm-slicing-5g-lab/logs/gNodeB_docker.log
interrupt_after: 30
reconfig_script_path: ../llm-slicing-5g-lab/change_rc_slice.sh

